// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SmartHomePanel

#ifndef _SMARTHOMEPANEL_UI_H
#define _SMARTHOMEPANEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_lamp_png);    // assets/lamp.png
LV_IMG_DECLARE(ui_img_curtain_png);    // assets/curtain.png
LV_IMG_DECLARE(ui_img_1202935209);    // assets/air-conditioning.png
LV_IMG_DECLARE(ui_img_plus_png);    // assets/plus.png
LV_IMG_DECLARE(ui_img_min_nimum_png);    // assets/min_nimum.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
